// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	handlers2 "tax-priority-api/src/application/faq/handlers"
	"tax-priority-api/src/infrastructure/persistence/repositories"
	"tax-priority-api/src/presentation/handlers"
)

// Injectors from faq_wire.go:

// InitializeFAQHTTPHandler инициализирует HTTP обработчик FAQ
func InitializeFAQHTTPHandler(db *gorm.DB) *handlers.FAQHTTPHandler {
	genericRepository := CreateFAQGenericRepository(db)
	faqRepository := repositories.NewFAQRepository(genericRepository)
	faqCommandHandlers := handlers2.NewFAQCommandHandlers(faqRepository)
	faqQueryHandlers := handlers2.NewFAQQueryHandlers(faqRepository)
	faqhttpHandler := handlers.NewFAQHTTPHandler(faqCommandHandlers, faqQueryHandlers)
	return faqhttpHandler
}

// faq_wire.go:

// FAQProviderSet набор провайдеров для FAQ
var FAQProviderSet = wire.NewSet(

	CreateFAQGenericRepository, repositories.NewFAQRepository, handlers2.NewFAQCommandHandlers, handlers2.NewFAQQueryHandlers, handlers.NewFAQHTTPHandler,
)
