// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/faq": {
            "get": {
                "description": "Возвращает список FAQ с пагинацией и фильтрацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить список FAQ",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Лимит записей",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "_offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "createdAt",
                        "description": "Поле сортировки",
                        "name": "_sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Порядок сортировки",
                        "name": "_order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по категории",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Фильтр по активности",
                        "name": "isActive",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PaginatedFAQResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новую запись FAQ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Создать FAQ",
                "parameters": [
                    {
                        "description": "Данные FAQ",
                        "name": "faq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateFAQRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.CommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/faq/batch": {
            "post": {
                "description": "Возвращает FAQ по списку ID (batch запрос)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить FAQ по списку ID",
                "parameters": [
                    {
                        "description": "Список ID",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_application_faq_queries.GetFAQsByIDsQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tax-priority-api_src_application_faq_dtos.FAQResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/faq/bulk-delete": {
            "post": {
                "description": "Удаляет несколько FAQ по списку ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Массовое удаление FAQ",
                "parameters": [
                    {
                        "description": "Список ID для удаления",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_application_faq_commands.BulkDeleteFAQCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_application_faq_dtos.BatchCommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/faq/categories": {
            "get": {
                "description": "Возвращает список категорий FAQ",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить категории FAQ",
                "parameters": [
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Включить количество FAQ в каждой категории",
                        "name": "withCounts",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tax-priority-api_src_application_faq_dtos.CategoryResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/faq/category/{category}": {
            "get": {
                "description": "Возвращает FAQ определенной категории",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить FAQ по категории",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Категория FAQ",
                        "name": "category",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Лимит записей",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "_offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "priority",
                        "description": "Поле сортировки",
                        "name": "_sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Порядок сортировки",
                        "name": "_order",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Только активные FAQ",
                        "name": "activeOnly",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tax-priority-api_src_application_faq_dtos.FAQResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/faq/count": {
            "get": {
                "description": "Возвращает общее количество FAQ",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить количество FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по категории",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Фильтр по активности",
                        "name": "isActive",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/faq/search": {
            "get": {
                "description": "Выполняет поиск FAQ по тексту",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Поиск FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поисковый запрос",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Категория для поиска",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Лимит записей",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "_offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "priority",
                        "description": "Поле сортировки",
                        "name": "_sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Порядок сортировки",
                        "name": "_order",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Только активные FAQ",
                        "name": "activeOnly",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tax-priority-api_src_application_faq_dtos.FAQResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/faq/{id}": {
            "get": {
                "description": "Возвращает FAQ по указанному ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить FAQ по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.FAQResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет существующую FAQ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Обновить FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "faq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_application_faq_commands.UpdateFAQCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_application_faq_dtos.CommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет FAQ по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Удалить FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_application_faq_dtos.CommandResult"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/faq/{id}/activate": {
            "patch": {
                "description": "Активирует FAQ по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Активировать FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_application_faq_dtos.CommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/faq/{id}/deactivate": {
            "patch": {
                "description": "Деактивирует FAQ по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Деактивировать FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_application_faq_dtos.CommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/api/faq/{id}/priority": {
            "patch": {
                "description": "Обновляет приоритет FAQ по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Обновить приоритет FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый приоритет",
                        "name": "priority",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_application_faq_commands.UpdateFAQPriorityCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_application_faq_dtos.CommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gin.H": {
            "type": "object",
            "additionalProperties": {}
        },
        "models.CommandResult": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2023-12-01T10:00:00Z"
                },
                "error": {
                    "type": "string",
                    "example": "Validation failed"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "message": {
                    "type": "string",
                    "example": "FAQ created successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-12-01T10:00:00Z"
                }
            }
        },
        "models.CreateFAQRequest": {
            "type": "object",
            "required": [
                "answer",
                "category",
                "question"
            ],
            "properties": {
                "answer": {
                    "type": "string",
                    "maxLength": 2000,
                    "minLength": 10,
                    "example": "Для подачи налоговой декларации необходимо..."
                },
                "category": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "налоги"
                },
                "priority": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0,
                    "example": 50
                },
                "question": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 10,
                    "example": "Как подать налоговую декларацию?"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Validation failed"
                }
            }
        },
        "models.FAQResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string",
                    "example": "Для подачи налоговой декларации необходимо..."
                },
                "category": {
                    "type": "string",
                    "example": "налоги"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2023-12-01T10:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "isActive": {
                    "type": "boolean",
                    "example": true
                },
                "priority": {
                    "type": "integer",
                    "example": 50
                },
                "question": {
                    "type": "string",
                    "example": "Как подать налоговую декларацию?"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-12-01T10:00:00Z"
                }
            }
        },
        "models.PaginatedFAQResponse": {
            "type": "object",
            "properties": {
                "hasNext": {
                    "type": "boolean",
                    "example": true
                },
                "hasPrev": {
                    "type": "boolean",
                    "example": false
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.FAQResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 100
                },
                "totalPages": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "tax-priority-api_src_application_faq_commands.BulkDeleteFAQCommand": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "tax-priority-api_src_application_faq_commands.UpdateFAQCommand": {
            "type": "object",
            "required": [
                "answer",
                "category",
                "id",
                "question"
            ],
            "properties": {
                "answer": {
                    "type": "string",
                    "maxLength": 2000,
                    "minLength": 10
                },
                "category": {
                    "type": "string",
                    "maxLength": 100
                },
                "id": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0
                },
                "question": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 10
                }
            }
        },
        "tax-priority-api_src_application_faq_commands.UpdateFAQPriorityCommand": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0
                }
            }
        },
        "tax-priority-api_src_application_faq_dtos.BatchCommandResult": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "failureCount": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tax-priority-api_src_application_faq_dtos.CommandResult"
                    }
                },
                "successCount": {
                    "type": "integer"
                }
            }
        },
        "tax-priority-api_src_application_faq_dtos.CategoryResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "tax-priority-api_src_application_faq_dtos.CommandResult": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "tax-priority-api_src_application_faq_dtos.FAQResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "priority": {
                    "type": "integer"
                },
                "question": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "tax-priority-api_src_application_faq_queries.GetFAQsByIDsQuery": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Tax Priority API",
	Description:      "REST API для управления FAQ в системе Tax Priority",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
