// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/faq": {
            "get": {
                "description": "Возвращает список FAQ с пагинацией и фильтрацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить список FAQ",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Лимит записей",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "_offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "createdAt",
                        "description": "Поле сортировки",
                        "name": "_sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Порядок сортировки",
                        "name": "_order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр по категории",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Фильтр по активности",
                        "name": "isActive",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.PaginatedFAQResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новую запись FAQ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Создать FAQ",
                "parameters": [
                    {
                        "description": "Данные FAQ",
                        "name": "faq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.CreateFAQRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.CommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/faq/batch": {
            "post": {
                "description": "Возвращает FAQ по списку ID (batch запрос)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить FAQ по списку ID",
                "parameters": [
                    {
                        "description": "Список ID",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.GetFAQsByIDsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tax-priority-api_src_presentation_models.FAQResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/faq/bulk-delete": {
            "delete": {
                "description": "Удаляет несколько FAQ по списку ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Массовое удаление FAQ",
                "parameters": [
                    {
                        "description": "Список ID для удаления",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.BulkDeleteFAQRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.BatchCommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/faq/categories": {
            "get": {
                "description": "Возвращает список категорий FAQ",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить категории FAQ",
                "parameters": [
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Включить количество FAQ в каждой категории",
                        "name": "withCounts",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tax-priority-api_src_presentation_models.CategoryResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/faq/category/{category}": {
            "get": {
                "description": "Возвращает FAQ определенной категории",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить FAQ по категории",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Категория FAQ",
                        "name": "category",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Лимит записей",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "_offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "priority",
                        "description": "Поле сортировки",
                        "name": "_sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Порядок сортировки",
                        "name": "_order",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Только активные FAQ",
                        "name": "activeOnly",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tax-priority-api_src_presentation_models.FAQResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/faq/count": {
            "get": {
                "description": "Возвращает общее количество FAQ",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить количество FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по категории",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Фильтр по активности",
                        "name": "isActive",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.CountResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/faq/search": {
            "get": {
                "description": "Выполняет поиск FAQ по тексту",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Поиск FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поисковый запрос",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Категория для поиска",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Лимит записей",
                        "name": "_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "_offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "priority",
                        "description": "Поле сортировки",
                        "name": "_sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "Порядок сортировки",
                        "name": "_order",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Только активные FAQ",
                        "name": "activeOnly",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tax-priority-api_src_presentation_models.FAQResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/faq/{id}": {
            "get": {
                "description": "Возвращает FAQ по указанному ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Получить FAQ по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.FAQResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет существующую FAQ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Обновить FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "faq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.UpdateFAQRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.CommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет FAQ по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Удалить FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.CommandResult"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/faq/{id}/activate": {
            "patch": {
                "description": "Активирует FAQ по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Активировать FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.CommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/faq/{id}/deactivate": {
            "patch": {
                "description": "Деактивирует FAQ по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Деактивировать FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.CommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/faq/{id}/priority": {
            "patch": {
                "description": "Обновляет приоритет FAQ по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FAQ"
                ],
                "summary": "Обновить приоритет FAQ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID FAQ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый приоритет",
                        "name": "priority",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.UpdateFAQPriorityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.CommandResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tax-priority-api_src_presentation_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "Устанавливает WebSocket соединение для получения уведомлений в реальном времени",
                "tags": [
                    "WebSocket"
                ],
                "summary": "WebSocket подключение",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID клиента (если не указан, будет сгенерирован)",
                        "name": "clientId",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/ws/broadcast": {
            "post": {
                "description": "Отправляет сообщение всем подключенным WebSocket клиентам",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WebSocket"
                ],
                "summary": "Широковещательное сообщение",
                "parameters": [
                    {
                        "description": "Сообщение для отправки",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/src_presentation_handlers.BroadcastMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/ws/info": {
            "get": {
                "description": "Возвращает подробную информацию о WebSocket подключениях",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WebSocket"
                ],
                "summary": "Информация о подключениях",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/src_presentation_handlers.ConnectionInfoResponse"
                        }
                    }
                }
            }
        },
        "/ws/stats": {
            "get": {
                "description": "Возвращает статистику WebSocket подключений и подписок",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WebSocket"
                ],
                "summary": "Статистика WebSocket",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ws/test": {
            "post": {
                "description": "Отправляет тестовое уведомление всем подключенным клиентам",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WebSocket"
                ],
                "summary": "Тестовое уведомление",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gin.H": {
            "type": "object",
            "additionalProperties": {}
        },
        "src_presentation_handlers.BroadcastMessageRequest": {
            "type": "object",
            "required": [
                "event"
            ],
            "properties": {
                "data": {},
                "event": {
                    "type": "string"
                }
            }
        },
        "src_presentation_handlers.ConnectionInfoResponse": {
            "type": "object",
            "properties": {
                "availableEvents": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "enabled": {
                    "type": "boolean"
                },
                "faqSubscribers": {
                    "type": "integer"
                },
                "serverTime": {
                    "type": "string"
                },
                "subscriptionTypes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "totalClients": {
                    "type": "integer"
                }
            }
        },
        "tax-priority-api_src_presentation_models.BatchCommandResult": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"Validation failed for item 1\"]"
                    ]
                },
                "failureCount": {
                    "type": "integer",
                    "example": 2
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tax-priority-api_src_presentation_models.CommandResult"
                    }
                },
                "successCount": {
                    "type": "integer",
                    "example": 8
                }
            }
        },
        "tax-priority-api_src_presentation_models.BulkDeleteFAQRequest": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"uuid1\"",
                        " \"uuid2\"]"
                    ]
                }
            }
        },
        "tax-priority-api_src_presentation_models.CategoryResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 25
                },
                "name": {
                    "type": "string",
                    "example": "налоги"
                }
            }
        },
        "tax-priority-api_src_presentation_models.CommandResult": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2023-12-01T10:00:00Z"
                },
                "error": {
                    "type": "string",
                    "example": "Validation failed"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "message": {
                    "type": "string",
                    "example": "FAQ created successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-12-01T10:00:00Z"
                }
            }
        },
        "tax-priority-api_src_presentation_models.CountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "tax-priority-api_src_presentation_models.CreateFAQRequest": {
            "type": "object",
            "required": [
                "answer",
                "category",
                "question"
            ],
            "properties": {
                "answer": {
                    "type": "string",
                    "maxLength": 2000,
                    "minLength": 10,
                    "example": "Для подачи налоговой декларации необходимо..."
                },
                "category": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "налоги"
                },
                "priority": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0,
                    "example": 50
                },
                "question": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 10,
                    "example": "Как подать налоговую декларацию?"
                }
            }
        },
        "tax-priority-api_src_presentation_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Validation failed"
                }
            }
        },
        "tax-priority-api_src_presentation_models.FAQResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string",
                    "example": "Для подачи налоговой декларации необходимо..."
                },
                "category": {
                    "type": "string",
                    "example": "налоги"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2023-12-01T10:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "isActive": {
                    "type": "boolean",
                    "example": true
                },
                "priority": {
                    "type": "integer",
                    "example": 50
                },
                "question": {
                    "type": "string",
                    "example": "Как подать налоговую декларацию?"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-12-01T10:00:00Z"
                }
            }
        },
        "tax-priority-api_src_presentation_models.GetFAQsByIDsRequest": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"uuid1\"",
                        " \"uuid2\"]"
                    ]
                }
            }
        },
        "tax-priority-api_src_presentation_models.PaginatedFAQResponse": {
            "type": "object",
            "properties": {
                "hasNext": {
                    "type": "boolean",
                    "example": true
                },
                "hasPrev": {
                    "type": "boolean",
                    "example": false
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tax-priority-api_src_presentation_models.FAQResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 100
                },
                "totalPages": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "tax-priority-api_src_presentation_models.UpdateFAQPriorityRequest": {
            "type": "object",
            "properties": {
                "priority": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0,
                    "example": 75
                }
            }
        },
        "tax-priority-api_src_presentation_models.UpdateFAQRequest": {
            "type": "object",
            "required": [
                "answer",
                "category",
                "question"
            ],
            "properties": {
                "answer": {
                    "type": "string",
                    "maxLength": 2000,
                    "minLength": 10,
                    "example": "Для подачи налоговой декларации необходимо..."
                },
                "category": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "налоги"
                },
                "priority": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0,
                    "example": 50
                },
                "question": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 10,
                    "example": "Как подать налоговую декларацию?"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Tax Priority API",
	Description:      "REST API для управления FAQ в системе Tax Priority",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
